<a href="https://colab.research.google.com/github/ajit1512/FedEx-Logistics-Performance-Analysis/blob/main/FedEx_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import All The Necessary Libraries
import pandas as pd
import numpy as np

In [2]:
# Load Dataset
Fedex_df = pd.read_csv('/content/SCMS_Delivery_History_Dataset.csv')
Fedex_df.head()

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.0,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.0,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.0,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.0,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [3]:
# No. of Ros and Columns
Fedex_df.shape

(10324, 33)

In [4]:
# Dataset Information
Fedex_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 9964 non-null   object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  object
 13  Delivered to Client Date      10324 non-null  object
 14  Delivery Recorded Date        10324 non-null  object
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        8588 non-null   object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            10324 non-null  object
 32  Line Item Insurance (USD)     10037 non-null  float64
dtypes: float64(4), int64(3), object(26)
memory usage: 2.6+ MB

In [5]:
# Name of Columns on this Dataset
Fedex_df.columns

Index(['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country',
       'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode',
       'PQ First Sent to Client Date', 'PO Sent to Vendor Date',
       'Scheduled Delivery Date', 'Delivered to Client Date',
       'Delivery Recorded Date', 'Product Group', 'Sub Classification',
       'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage',
       'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity',
       'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site',
       'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)',
       'Line Item Insurance (USD)'],
      dtype='object')

In [6]:
# Describe Dataset
Fedex_df.describe()

,ID,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Line Item Insurance (USD)
count,10324.000000,10324.000000,10324.000000,1.032400e+04,10324.000000,10324.000000,10037.000000
mean,51098.968229,77.990895,18332.534870,1.576506e+05,21.910241,0.611701,240.117626
std,31944.332496,76.579764,40035.302961,3.452921e+05,45.609223,3.275808,500.190568
min,1.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,12795.750000,30.000000,408.000000,4.314593e+03,4.120000,0.080000,6.510000
50%,57540.500000,60.000000,3000.000000,3.047147e+04,9.300000,0.160000,47.040000
75%,83648.250000,90.000000,17039.750000,1.664471e+05,23.592500,0.470000,252.400000
max,86823.000000,1000.000000,619999.000000,5.951990e+06,1345.640000,238.650000,7708.440000

In [7]:
# Check Unique Values for each variable.
Fedex_df.nunique()

ID                              10324
Project Code                      142
PQ #                             1237
PO / SO #                        6233
ASN/DN #                         7030
Country                            43
Managed By                          4
Fulfill Via                         2
Vendor INCO Term                    8
Shipment Mode                       4
PQ First Sent to Client Date      765
PO Sent to Vendor Date            897
Scheduled Delivery Date          2006
Delivered to Client Date         2093
Delivery Recorded Date           2042
Product Group                       5
Sub Classification                  6
Vendor                             73
Item Description                  184
Molecule/Test Type                 86
Brand                              48
Dosage                             54
Dosage Form                        17
Unit of Measure (Per Pack)         31
Line Item Quantity               5065
Line Item Value                  8741
Pack Price                       1175
Unit Price                        183
Manufacturing Site                 88
First Line Designation              2
Weight (Kilograms)               4688
Freight Cost (USD)               6733
Line Item Insurance (USD)        6722
dtype: int64

***Data Cleaning Process***

In [8]:
# let's perform the data cleaning task
# Primarily We Will Check the null Values in each colunns
Fedex_df.isnull().sum()              # As we can see here Columns "Shipment Mode", "Dosage" and "Line Item Insurance (USD)" contains the null values

ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

In [9]:
for shipment_mode, count in Fedex_df['Shipment Mode'].value_counts().items():
  print(f"{shipment_mode} : {count}")

Air : 6113
Truck : 2830
Air Charter : 650
Ocean : 371

In [10]:
# As we can see here large no of Shipment made by "Air", So Here we will replace all the null values with "Air" in Shipment Mode Column
Fedex_df['Shipment Mode'] = Fedex_df['Shipment Mode'].fillna('Air')

In [11]:
# Similarly Do Here for "Dosage" Column
Mode_of_Dosage = Fedex_df['Dosage'].mode()[0]
Fedex_df['Dosage'].fillna(Mode_of_Dosage, inplace = True)

<ipython-input-11-2afb6a29ccab>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Fedex_df['Dosage'].fillna(Mode_of_Dosage, inplace = True)

In [12]:
Fedex_df['Line Item Insurance (USD)'].unique()

array([    nan,  192.  ,  128.  , ..., 5284.04,  134.03,   85.82])

In [13]:
# For "Line Item Insurance (USD)" Column first we will find the mean of it and then replace all nan values with it
Fedex_df['Line Item Insurance (USD)'].fillna(Fedex_df['Line Item Insurance (USD)'].mean(), inplace=True)

<ipython-input-13-9d67458c5ea0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Fedex_df['Line Item Insurance (USD)'].fillna(Fedex_df['Line Item Insurance (USD)'].mean(), inplace=True)

In [14]:
# Lets Check Duplicate Data
Fedex_df.duplicated().sum()

0

In [15]:
# Now lets save dataset for visualization
Fedex_df.to_csv('Fedex.csv', index=False)